name: Run tests

on: [pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run install
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install Ion
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: AWS test
        run: aws sts get-caller-identity

      - name: Test sst
        run: |
          pnpm deploy:staging
